[2025-02-12T18:07:24.768+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T18:07:24.799+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.extract_data manual__2025-02-12T18:06:46.898638+00:00 [queued]>
[2025-02-12T18:07:24.820+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.extract_data manual__2025-02-12T18:06:46.898638+00:00 [queued]>
[2025-02-12T18:07:24.864+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T18:07:25.475+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-12 18:06:46.898638+00:00
[2025-02-12T18:07:25.851+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1638) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T18:07:25.857+0000] {standard_task_runner.py:72} INFO - Started process 1640 to run task
[2025-02-12T18:07:25.857+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19_ETL_v2.1', 'extract_data', 'manual__2025-02-12T18:06:46.898638+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/covid_test.py', '--cfg-path', '/tmp/tmpihgnaf61']
[2025-02-12T18:07:25.865+0000] {standard_task_runner.py:105} INFO - Job 154: Subtask extract_data
[2025-02-12T18:07:25.981+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19_ETL_v2.1.extract_data manual__2025-02-12T18:06:46.898638+00:00 [running]> on host f99369d27a52
[2025-02-12T18:07:27.437+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19_ETL_v2.1' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T18:06:46.898638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T18:06:46.898638+00:00'
[2025-02-12T18:07:27.440+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T18:07:27.482+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T18:07:28.299+0000] {covid_test.py:31} INFO - Trying https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-30-2020.csv
[2025-02-12T18:07:29.974+0000] {covid_test.py:53} INFO - Successfully fetched data for 2020-01-30
[2025-02-12T18:07:29.976+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-12T18:07:29.989+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T18:07:29.990+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19_ETL_v2.1, task_id=extract_data, run_id=manual__2025-02-12T18:06:46.898638+00:00, execution_date=20250212T180646, start_date=20250212T180724, end_date=20250212T180729
[2025-02-12T18:07:30.041+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T18:07:30.079+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-12T18:07:30.083+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
