[2025-02-12T17:47:43.994+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T17:47:44.173+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.extract_data scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T17:47:44.274+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.extract_data scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T17:47:44.275+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T17:47:44.341+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-11 00:00:00+00:00
[2025-02-12T17:47:44.401+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1364) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T17:47:44.484+0000] {standard_task_runner.py:72} INFO - Started process 1366 to run task
[2025-02-12T17:47:44.497+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19_ETL_v2.1', 'extract_data', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/covid_test.py', '--cfg-path', '/tmp/tmpi_47shhs']
[2025-02-12T17:47:44.522+0000] {standard_task_runner.py:105} INFO - Job 142: Subtask extract_data
[2025-02-12T17:47:44.833+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19_ETL_v2.1.extract_data scheduled__2025-02-11T00:00:00+00:00 [running]> on host f99369d27a52
[2025-02-12T17:48:03.750+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19_ETL_v2.1' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-12T17:48:03.753+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T17:48:03.914+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T17:48:03.955+0000] {covid_test.py:31} INFO - Trying https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-30-2020.csv
[2025-02-12T17:48:05.381+0000] {covid_test.py:53} INFO - Successfully fetched data for 2020-01-30
[2025-02-12T17:48:05.400+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-12T17:48:05.450+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T17:48:05.466+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19_ETL_v2.1, task_id=extract_data, run_id=scheduled__2025-02-11T00:00:00+00:00, execution_date=20250211T000000, start_date=20250212T174744, end_date=20250212T174805
[2025-02-12T17:48:05.706+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T17:48:07.710+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-12T17:48:07.716+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
