[2025-02-12T07:11:17.997+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T07:11:18.075+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19.create_dim_date manual__2025-02-12T07:10:30.082068+00:00 [queued]>
[2025-02-12T07:11:18.117+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19.create_dim_date manual__2025-02-12T07:10:30.082068+00:00 [queued]>
[2025-02-12T07:11:18.123+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T07:11:18.240+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_dim_date> on 2025-02-12 07:10:30.082068+00:00
[2025-02-12T07:11:18.310+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=605) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T07:11:18.383+0000] {standard_task_runner.py:72} INFO - Started process 617 to run task
[2025-02-12T07:11:18.361+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19', 'create_dim_date', 'manual__2025-02-12T07:10:30.082068+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/covid_19.py', '--cfg-path', '/tmp/tmpf9wavb8o']
[2025-02-12T07:11:18.413+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask create_dim_date
[2025-02-12T07:11:32.675+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19.create_dim_date manual__2025-02-12T07:10:30.082068+00:00 [running]> on host e0d8147cd68a
[2025-02-12T07:11:33.435+0000] {job.py:229} INFO - Heartbeat recovered after 16.09 seconds
[2025-02-12T07:11:34.328+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19' AIRFLOW_CTX_TASK_ID='create_dim_date' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T07:10:30.082068+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T07:10:30.082068+00:00'
[2025-02-12T07:11:34.342+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T07:11:34.576+0000] {sql.py:278} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS dim_date (
        date_id SERIAL PRIMARY KEY,
        date DATE NOT NULL,
        year INTEGER,
        month INTEGER,
        day INTEGER,
        weekday VARCHAR(10),
        is_weekend BOOLEAN
        );
        
[2025-02-12T07:11:34.651+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T07:11:34.744+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T07:11:34.777+0000] {sql.py:553} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS dim_date (
        date_id SERIAL PRIMARY KEY,
        date DATE NOT NULL,
        year INTEGER,
        month INTEGER,
        day INTEGER,
        weekday VARCHAR(10),
        is_weekend BOOLEAN
        );
        , parameters: None
[2025-02-12T07:11:34.841+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T07:11:34.844+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19, task_id=create_dim_date, run_id=manual__2025-02-12T07:10:30.082068+00:00, execution_date=20250212T071030, start_date=20250212T071118, end_date=20250212T071134
[2025-02-12T07:11:35.025+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T07:11:37.848+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-02-12T07:11:37.863+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
