[2025-02-12T18:00:49.109+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T18:00:49.146+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.extract_data manual__2025-02-12T17:59:30.349187+00:00 [queued]>
[2025-02-12T18:00:49.173+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.extract_data manual__2025-02-12T17:59:30.349187+00:00 [queued]>
[2025-02-12T18:00:49.174+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T18:00:49.208+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-12 17:59:30.349187+00:00
[2025-02-12T18:00:49.233+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1553) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T18:00:49.241+0000] {standard_task_runner.py:72} INFO - Started process 1555 to run task
[2025-02-12T18:00:49.238+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19_ETL_v2.1', 'extract_data', 'manual__2025-02-12T17:59:30.349187+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/covid_test.py', '--cfg-path', '/tmp/tmp7jg4zhir']
[2025-02-12T18:00:49.244+0000] {standard_task_runner.py:105} INFO - Job 151: Subtask extract_data
[2025-02-12T18:00:49.368+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19_ETL_v2.1.extract_data manual__2025-02-12T17:59:30.349187+00:00 [running]> on host f99369d27a52
[2025-02-12T18:00:53.081+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19_ETL_v2.1' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T17:59:30.349187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T17:59:30.349187+00:00'
[2025-02-12T18:00:53.084+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T18:00:53.243+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T18:00:53.262+0000] {covid_test.py:31} INFO - Trying https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-30-2020.csv
[2025-02-12T18:00:53.925+0000] {covid_test.py:53} INFO - Successfully fetched data for 2020-01-30
[2025-02-12T18:00:53.930+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-12T18:00:53.951+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T18:00:53.954+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19_ETL_v2.1, task_id=extract_data, run_id=manual__2025-02-12T17:59:30.349187+00:00, execution_date=20250212T175930, start_date=20250212T180049, end_date=20250212T180053
[2025-02-12T18:00:54.035+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T18:00:54.170+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T18:00:54.177+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
