[2025-02-13T08:06:07.689+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T08:06:07.711+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19_ETL.extract_data manual__2025-02-13T08:05:44.686326+00:00 [queued]>
[2025-02-13T08:06:07.730+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19_ETL.extract_data manual__2025-02-13T08:05:44.686326+00:00 [queued]>
[2025-02-13T08:06:07.731+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-13T08:06:07.749+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-13 08:05:44.686326+00:00
[2025-02-13T08:06:07.763+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=588) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T08:06:07.765+0000] {standard_task_runner.py:72} INFO - Started process 590 to run task
[2025-02-13T08:06:07.766+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19_ETL', 'extract_data', 'manual__2025-02-13T08:05:44.686326+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/covid_19.py', '--cfg-path', '/tmp/tmppgww847n']
[2025-02-13T08:06:07.770+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask extract_data
[2025-02-13T08:06:07.855+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19_ETL.extract_data manual__2025-02-13T08:05:44.686326+00:00 [running]> on host 3b43358e3e84
[2025-02-13T08:06:08.257+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19_ETL' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T08:05:44.686326+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T08:05:44.686326+00:00'
[2025-02-13T08:06:08.265+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-13T08:06:08.326+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-13T08:06:08.343+0000] {covid_19.py:31} INFO - Trying https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-04-2020.csv
[2025-02-13T08:06:10.294+0000] {covid_19.py:52} INFO - Successfully fetched data for 2020-02-04
[2025-02-13T08:06:10.298+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-13T08:06:10.318+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-13T08:06:10.319+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19_ETL, task_id=extract_data, run_id=manual__2025-02-13T08:05:44.686326+00:00, execution_date=20250213T080544, start_date=20250213T080607, end_date=20250213T080610
[2025-02-13T08:06:10.397+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T08:06:10.713+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-13T08:06:10.770+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
