[2025-02-12T06:53:14.341+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T06:53:14.371+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19.create_fact_table manual__2025-02-12T06:52:31.631474+00:00 [queued]>
[2025-02-12T06:53:14.392+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19.create_fact_table manual__2025-02-12T06:52:31.631474+00:00 [queued]>
[2025-02-12T06:53:14.394+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T06:53:14.436+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_fact_table> on 2025-02-12 06:52:31.631474+00:00
[2025-02-12T06:53:14.456+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=345) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T06:53:14.460+0000] {standard_task_runner.py:72} INFO - Started process 347 to run task
[2025-02-12T06:53:14.459+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19', 'create_fact_table', 'manual__2025-02-12T06:52:31.631474+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/covid_19.py', '--cfg-path', '/tmp/tmp2qcg3e9g']
[2025-02-12T06:53:14.466+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask create_fact_table
[2025-02-12T06:53:15.055+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19.create_fact_table manual__2025-02-12T06:52:31.631474+00:00 [running]> on host e0d8147cd68a
[2025-02-12T06:53:15.252+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19' AIRFLOW_CTX_TASK_ID='create_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T06:52:31.631474+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T06:52:31.631474+00:00'
[2025-02-12T06:53:15.260+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T06:53:15.301+0000] {sql.py:278} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS fact_covid_cases (
        case_id SERIAL PRIMARY KEY,
        date_id INTEGER REFERENCES dim_date(date_id),
        location_id INTEGER REFERENCES dim_location(location_id),
        confirmed INTEGER,
        deaths INTEGER,
        recovered INTEGER,
        active INTEGER,
        incident_rate FLOAT,
        case_fatality_ratio FLOAT
        );
[2025-02-12T06:53:15.345+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T06:53:15.399+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T06:53:15.412+0000] {sql.py:553} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS fact_covid_cases (
        case_id SERIAL PRIMARY KEY,
        date_id INTEGER REFERENCES dim_date(date_id),
        location_id INTEGER REFERENCES dim_location(location_id),
        confirmed INTEGER,
        deaths INTEGER,
        recovered INTEGER,
        active INTEGER,
        incident_rate FLOAT,
        case_fatality_ratio FLOAT
        );, parameters: None
[2025-02-12T06:53:15.436+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T06:53:15.438+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19, task_id=create_fact_table, run_id=manual__2025-02-12T06:52:31.631474+00:00, execution_date=20250212T065231, start_date=20250212T065314, end_date=20250212T065315
[2025-02-12T06:53:15.510+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T06:53:16.178+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-12T06:53:16.188+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
