[2025-02-12T17:57:16.012+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T17:57:16.058+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.extract_data manual__2025-02-12T17:56:27.144775+00:00 [queued]>
[2025-02-12T17:57:16.081+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.extract_data manual__2025-02-12T17:56:27.144775+00:00 [queued]>
[2025-02-12T17:57:16.082+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T17:57:16.107+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-12 17:56:27.144775+00:00
[2025-02-12T17:57:16.138+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1497) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T17:57:16.143+0000] {standard_task_runner.py:72} INFO - Started process 1499 to run task
[2025-02-12T17:57:16.144+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19_ETL_v2.1', 'extract_data', 'manual__2025-02-12T17:56:27.144775+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/covid_test.py', '--cfg-path', '/tmp/tmpb9q7x0b2']
[2025-02-12T17:57:16.148+0000] {standard_task_runner.py:105} INFO - Job 148: Subtask extract_data
[2025-02-12T17:57:16.275+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19_ETL_v2.1.extract_data manual__2025-02-12T17:56:27.144775+00:00 [running]> on host f99369d27a52
[2025-02-12T17:57:17.725+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19_ETL_v2.1' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T17:56:27.144775+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T17:56:27.144775+00:00'
[2025-02-12T17:57:17.728+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T17:57:17.787+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T17:57:17.803+0000] {covid_test.py:31} INFO - Trying https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-30-2020.csv
[2025-02-12T17:57:18.423+0000] {covid_test.py:53} INFO - Successfully fetched data for 2020-01-30
[2025-02-12T17:57:18.431+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-12T17:57:18.454+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T17:57:18.455+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19_ETL_v2.1, task_id=extract_data, run_id=manual__2025-02-12T17:56:27.144775+00:00, execution_date=20250212T175627, start_date=20250212T175716, end_date=20250212T175718
[2025-02-12T17:57:18.560+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T17:57:18.595+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-12T17:57:18.601+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
